# Gradle
# Build your Java projects and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/java

resources:
  containers:
  - container: ubuntu18
    image: ubuntu:18.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

jobs:
  - job: Styleguide
    pool:
      vmImage: 'Ubuntu 16.04'

    container: ubuntu18

    steps:
        - script: |
            /tmp/docker exec -t -u 0 ci-container \
            sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
          displayName: Set up sudo
        - script: |
            sudo add-apt-repository ppa:inkscape.dev/stable -y
            sudo apt-get update -y
            sudo apt-get install inkscape imagemagick -y
            pip install --user yapf
          displayName: 'Install Dependencies'
        - script: |
            inkscape --version
            python3 -m yapf --style google -i export.py rasterize.py
            ./export.py
            # Ensure yapf and export.py made no changes
            git --no-pager diff --exit-code HEAD
          displayName: 'Test'
